TRUTH = (
    "Apakah kamu pernah membuat hantu seseorang?" "Apakah kamu pernah berjalan di atas orang tuamu melakukan 'itu'?",
    "Siapa orang terakhir yang paling kamu sukai? Mengapa?",
    "Apakah kamu pernah diskors dari sekolah?",
    "Jika Anda harus memilih antara telanjang atau pikiran Anda muncul dalam gelembung pikiran di atas kepala Anda untuk dibaca semua orang, mana yang akan Anda pilih?",
    "Apa satu hal yang kamu takut kehilangan?",
    "Apakah kamu menyukai seseorang saat ini?",
    "Satu hal tentang sahabatmu yang membuatmu cemburu?",
    "Apakah kamu akan menipu pacarmu untuk pria kaya?",
    "Apa giliran terbesarmu?",
    "Kapan terakhir kali kamu berbohong kepada orang tuamu dan mengapa?",
    "Jelaskan pasangan ideal Anda.",
    "Apakah kamu menyukai @fckualot ?",
    "Apa hal paling menakutkan yang pernah kamu lakukan?",
    "Apakah kamu pernah mengupil dan memakannya?",
    "Kapan terakhir kali kamu berbohong kepada orang tuamu dan mengapa?",
    "Apakah Anda pernah berbohong tentang usia Anda untuk berpartisipasi dalam kontes?",
    "Apakah kamu pernah ketahuan sedang memeriksa seseorang?",
)

DARE = (
    "Tampilkan foto paling memalukan di ponsel Anda"
    "Tampilkan lima orang terakhir yang Anda kirimi SMS dan apa isi pesannya",
    "Biarkan seluruh grup DM seseorang dari akun Instagram Anda",
    "Makan bawang putih mentah",
    "Lakukan 100 squat",
    "Beri tahu @anonymous_was_bot bahwa kamu mencintainya.",
    "Simpan tiga es batu di mulutmu sampai meleleh",
    "Katakan sesuatu yang kotor kepada orang di sebelah kirimu. Kamu punya teman!",
    "Berikan pijatan kaki pada orang di sebelah kanan Anda",
    "Masukkan 10 cairan berbeda yang tersedia ke dalam cangkir dan minumlah",
    "* Ucapkan kata pertama yang muncul di pikiranmu",
    "Berikan lap dance kepada seseorang pilihan Anda",
    "Lepaskan empat potong pakaian",
    "Suka 15 posting pertama di umpan berita Facebook Anda",
    "Makan sesendok mustard",
    "Pejamkan matamu sampai kamu pergi lagi",
    "Kirim sext ke orang terakhir di buku telepon Anda",
    "Pamerkan wajah orgasme Anda",
    "Menggoda makan pisang",
    "Kosongkan dompet/dompet Anda dan tunjukkan kepada semua orang apa yang ada di dalamnya",
    "Lakukan perayapan seksi terbaikmu",
    "Berpura-puralah menjadi orang di sebelah kananmu selama 10 menit",
    "Makan snack tanpa menggunakan tangan",
    "Katakan dua hal jujur ​​tentang semua orang dalam grup",
    "Twerk sebentar",
    "Cobalah membuat grup tertawa secepat mungkin",
    "Cobalah untuk memasukkan seluruh kepalan tanganmu ke dalam mulutmu",
    "Ceritakan kepada semua orang kisah memalukan tentang dirimu",
    "Coba jilat sikumu",
    "Posting selfie tertua di ponsel Anda di Instagram Stories",
    "Ceritakan kisah paling menyedihkan yang kamu tahu",
    "Melolong seperti serigala selama dua menit",
    "Menari tanpa musik selama dua menit",
    "Tari tiang dengan tiang imajiner",
    "Biarkan orang lain menggelitikmu dan mencoba untuk tidak tertawa",
    "Masukkan makanan ringan ke dalam mulut Anda sekaligus sebanyak yang Anda bisa",
    "Kirim selfie terbaru Anda.",
    "Kirim selfie terjelekmu.",
    "Kirim tangkapan layar riwayat pencarian facebook Anda",
    "Kirim tangkapan layar galeri Anda.",
    "Kirim tangkapan layar kotak masuk messenger Anda",
    "Katakan sesuatu yang sangat intim.",
    "Kirim tangkapan layar kotak masuk twitter Anda",
    "Kirim tangkapan layar layar beranda Anda.",
    "Kirim cover lagu favoritmu. ",
    "Lakukan lelucon lirik pada seseorang dan kirimkan buktinya.",
    "Akui naksir Anda saat ini. ❤️",
    "Nyatakan siapa cinta sejatimu.",
    "Kirim tangkapan layar galeri Anda.",
    "Jadikan foto gebetanmu sebagai dpmu.",
    "Sarankan saya lebih berani.",
)
